; Büyük dosya yükleme için
upload_max_filesize = 1200M
post_max_size       = 1300M
memory_limit        = 512M
max_execution_time  = 600
max_input_time      = 600

; Güvenlik
expose_php         = Off
display_errors     = Off
log_errors         = On
error_log          = /var/www/html/storage/logs/php_error.log

; Session
session.cookie_httponly = 1
session.cookie_secure   = 1
session.cookie_samesite = Lax

; Timezone
date.timezone = Europe/Istanbul
